/*
 *  /Users/ken/Projects/abst-hier/src/gitHub.com/Ken1JF/GenSGFProperties/SGF_Property_gen.h
 *  GenSGFProperties
 *
 *  Generated by GenSGFProperties Version FF[4] 1.0 on Jan  1 2014 at 19:19:26
 *  Copyright 2007- 2014 Ken Friedenbach. All rights reserved.
 *
 */

sgfPropDef SGF_prop_AB("AB", SGF_std,        "Add Black",        SGF_setup_prop_type,        SGF_no_qual,      SGF_stone_list                );
sgfPropDef SGF_prop_AE("AE", SGF_std,        "Add Empty",        SGF_setup_prop_type,        SGF_no_qual,      SGF_point_list                );
sgfPropDef SGF_prop_AN("AN", SGF_std,        "Annotation",       SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_AP("AP", SGFF4_new,      "Application",      SGF_root_prop_type,         SGF_no_qual,      SGF_comp_simtxt               );
sgfPropDef SGF_prop_AR("AR", SGFF4_new,      "Arrow",            SGF_no_prop_type,           SGF_no_qual,      SGF_list_comp_point           );
sgfPropDef SGF_prop_AS("AS", SGFF4_new,      "Who adds stones",  SGF_no_prop_type,           SGF_LOA_only,     SGF_simpletext                );
sgfPropDef SGF_prop_AW("AW", SGF_std,        "Add White",        SGF_setup_prop_type,        SGF_no_qual,      SGF_stone_list                );
sgfPropDef SGF_prop_B ("B",  SGF_std,        "Black",            SGF_move_prop_type,         SGF_no_qual,      SGF_move                      );
sgfPropDef SGF_prop_BL("BL", SGF_std,        "Black time left",  SGF_move_prop_type,         SGF_no_qual,      SGF_real                      );
sgfPropDef SGF_prop_BM("BM", SGF_std,        "Bad move",         SGF_move_prop_type,         SGF_no_qual,      SGF_double                    );
sgfPropDef SGF_prop_BR("BR", SGF_std,        "Black rank",       SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_BT("BT", SGF_std,        "Black team",       SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_C ("C",  SGF_std,        "Comment",          SGF_no_prop_type,           SGF_no_qual,      SGF_text                      );
sgfPropDef SGF_prop_CA("CA", SGFF4_new,      "Charset",          SGF_root_prop_type,         SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_CP("CP", SGF_std,        "Copyright",        SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_CR("CR", SGF_std,        "Circle",           SGF_no_prop_type,           SGF_no_qual,      SGF_point_list                );
sgfPropDef SGF_prop_DD("DD", SGFF4_new,      "Dim points",       SGF_no_prop_type,           SGF_inherit,      SGF_point_elist               );
sgfPropDef SGF_prop_DM("DM", SGF_std,        "Even position",    SGF_no_prop_type,           SGF_no_qual,      SGF_double                    );
sgfPropDef SGF_prop_DO("DO", SGF_std,        "Doubtful",         SGF_move_prop_type,         SGF_no_qual,      SGF_no_value                  );
sgfPropDef SGF_prop_DT("DT", SGFF4_changed,  "Date",             SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_EV("EV", SGF_std,        "Event",            SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_FF("FF", SGF_std,        "Fileformat",       SGF_root_prop_type,         SGF_no_qual,      SGF_FF_number                 );
sgfPropDef SGF_prop_FG("FG", SGFF4_changed,  "Figure",           SGF_no_prop_type,           SGF_no_qual,      SGF_none_or_comp_num_simtxt   );
sgfPropDef SGF_prop_GB("GB", SGF_std,        "Good for Black",   SGF_no_prop_type,           SGF_no_qual,      SGF_double                    );
sgfPropDef SGF_prop_GC("GC", SGF_std,        "Game comment",     SGF_game_info_prop_type,    SGF_no_qual,      SGF_text                      );
sgfPropDef SGF_prop_GM("GM", SGF_std,        "Game",             SGF_root_prop_type,         SGF_no_qual,      SGF_game_number               );
sgfPropDef SGF_prop_GN("GN", SGF_std,        "Game name",        SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_GW("GW", SGF_std,        "Good for White",   SGF_no_prop_type,           SGF_no_qual,      SGF_double                    );
sgfPropDef SGF_prop_HA("HA", SGF_std,        "Handicap",         SGF_game_info_prop_type,    SGF_Go_only,      SGF_number                    );
sgfPropDef SGF_prop_HO("HO", SGF_std,        "Hotspot",          SGF_no_prop_type,           SGF_no_qual,      SGF_double                    );
sgfPropDef SGF_prop_IP("IP", SGFF4_new,      "Initial pos.",     SGF_game_info_prop_type,    SGF_LOA_only,     SGF_simpletext                );
sgfPropDef SGF_prop_IT("IT", SGF_std,        "Interesting",      SGF_move_prop_type,         SGF_no_qual,      SGF_no_value                  );
sgfPropDef SGF_prop_IY("IY", SGFF4_new,      "Invert Y-axis",    SGF_game_info_prop_type,    SGF_LOA_only,     SGF_simpletext                );
sgfPropDef SGF_prop_KM("KM", SGF_std,        "Komi",             SGF_game_info_prop_type,    SGF_Go_only,      SGF_real                      );
sgfPropDef SGF_prop_KO("KO", SGF_std,        "Ko",               SGF_move_prop_type,         SGF_no_qual,      SGF_no_value                  );
sgfPropDef SGF_prop_LB("LB", SGFF4_changed,  "Label",            SGF_no_prop_type,           SGF_no_qual,      SGF_list_comp_point_simtxt    );
sgfPropDef SGF_prop_LN("LN", SGFF4_new,      "Line",             SGF_no_prop_type,           SGF_no_qual,      SGF_list_comp_point           );
sgfPropDef SGF_prop_MA("MA", SGF_std,        "Mark",             SGF_no_prop_type,           SGF_no_qual,      SGF_point_list                );
sgfPropDef SGF_prop_MN("MN", SGF_std,        "set move number",  SGF_move_prop_type,         SGF_no_qual,      SGF_number                    );
sgfPropDef SGF_prop_N ("N",  SGF_std,        "Nodename",         SGF_no_prop_type,           SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_OB("OB", SGF_std,        "OtStones Black",   SGF_move_prop_type,         SGF_no_qual,      SGF_number                    );
sgfPropDef SGF_prop_OH("OH", SGF_non_std,    "Old Handicap",     SGF_game_info_prop_type,    SGF_no_qual,      SGF_text                      );
sgfPropDef SGF_prop_ON("ON", SGF_std,        "Opening",          SGF_game_info_prop_type,    SGF_no_qual,      SGF_text                      );
sgfPropDef SGF_prop_OT("OT", SGFF4_new,      "Overtime",         SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_OW("OW", SGF_std,        "OtStones White",   SGF_move_prop_type,         SGF_no_qual,      SGF_number                    );
sgfPropDef SGF_prop_PB("PB", SGF_std,        "Player Black",     SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_PC("PC", SGF_std,        "Place",            SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_PL("PL", SGF_std,        "Player to play",   SGF_setup_prop_type,        SGF_no_qual,      SGF_color                     );
sgfPropDef SGF_prop_PM("PM", SGFF4_new,      "Print move mode",  SGF_no_prop_type,           SGF_inherit,      SGF_number                    );
sgfPropDef SGF_prop_PW("PW", SGF_std,        "Player White",     SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_RE("RE", SGFF4_changed,  "Result",           SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_RO("RO", SGF_std,        "Round",            SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_RU("RU", SGFF4_changed,  "Rules",            SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_S ("S",  SGF_non_std,    "Sequence",         SGF_move_prop_type,         SGC_extension,    SGC_compressed_list_point     );
sgfPropDef SGF_prop_SE("SE", SGFF4_new,      "Markup",           SGF_no_prop_type,           SGF_LOA_only,     SGF_point                     );
sgfPropDef SGF_prop_SL("SL", SGF_std,        "Selected",         SGF_no_prop_type,           SGF_no_qual,      SGF_point_list                );
sgfPropDef SGF_prop_SO("SO", SGF_std,        "Source",           SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_SQ("SQ", SGFF4_new,      "Square",           SGF_no_prop_type,           SGF_no_qual,      SGF_point_list                );
sgfPropDef SGF_prop_ST("ST", SGFF4_new,      "Style",            SGF_root_prop_type,         SGF_no_qual,      SGF_ST_number                 );
sgfPropDef SGF_prop_SU("SU", SGFF4_new,      "Setup type",       SGF_game_info_prop_type,    SGF_LOA_only,     SGF_simpletext                );
sgfPropDef SGF_prop_SZ("SZ", SGFF4_changed,  "Size",             SGF_root_prop_type,         SGF_no_qual,      SGF_num_or_comp_num           );
sgfPropDef SGF_prop_TB("TB", SGF_std,        "Territory Black",  SGF_no_prop_type,           SGF_Go_only,      SGF_point_elist               );
sgfPropDef SGF_prop_TE("TE", SGF_std,        "Tesuji",           SGF_move_prop_type,         SGF_no_qual,      SGF_double                    );
sgfPropDef SGF_prop_TM("TM", SGF_std,        "Timelimit",        SGF_game_info_prop_type,    SGF_no_qual,      SGF_real                      );
sgfPropDef SGF_prop_TR("TR", SGF_std,        "Triangle",         SGF_no_prop_type,           SGF_no_qual,      SGF_point_list                );
sgfPropDef SGF_prop_TW("TW", SGF_std,        "Territory White",  SGF_no_prop_type,           SGF_Go_only,      SGF_point_elist               );
sgfPropDef SGF_prop_UC("UC", SGF_std,        "Unclear pos",      SGF_no_prop_type,           SGF_no_qual,      SGF_double                    );
sgfPropDef SGF_prop_US("US", SGF_std,        "User",             SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_V ("V",  SGF_std,        "Value",            SGF_no_prop_type,           SGF_no_qual,      SGF_real                      );
sgfPropDef SGF_prop_VW("VW", SGFF4_new,      "View",             SGF_no_prop_type,           SGF_inherit,      SGF_point_elist               );
sgfPropDef SGF_prop_W ("W",  SGF_std,        "White",            SGF_move_prop_type,         SGF_no_qual,      SGF_move                      );
sgfPropDef SGF_prop_WB("WB", SGF_non_std,    "Wins Black",       SGF_move_prop_type,         SGF_no_qual,      SGF_number                    );
sgfPropDef SGF_prop_WC("WC", SGF_non_std,    "Win Continue",     SGF_move_prop_type,         SGF_no_qual,      SGF_comp_simtxt               );
sgfPropDef SGF_prop_WL("WL", SGF_std,        "White time left",  SGF_move_prop_type,         SGF_no_qual,      SGF_real                      );
sgfPropDef SGF_prop_WO("WO", SGF_non_std,    "Wins Other",       SGF_move_prop_type,         SGF_no_qual,      SGF_number                    );
sgfPropDef SGF_prop_WR("WR", SGF_std,        "White rank",       SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_WT("WT", SGF_std,        "White team",       SGF_game_info_prop_type,    SGF_no_qual,      SGF_simpletext                );
sgfPropDef SGF_prop_WW("WW", SGF_non_std,    "Wins White",       SGF_move_prop_type,         SGF_no_qual,      SGF_number                    );
sgfPropDef * the_SGF_Properties[] = 
{
    &SGF_prop_AB,
    &SGF_prop_AE,
    &SGF_prop_AN,
    &SGF_prop_AP,
    &SGF_prop_AR,
    &SGF_prop_AS,
    &SGF_prop_AW,
    &SGF_prop_B ,
    &SGF_prop_BL,
    &SGF_prop_BM,
    &SGF_prop_BR,
    &SGF_prop_BT,
    &SGF_prop_C ,
    &SGF_prop_CA,
    &SGF_prop_CP,
    &SGF_prop_CR,
    &SGF_prop_DD,
    &SGF_prop_DM,
    &SGF_prop_DO,
    &SGF_prop_DT,
    &SGF_prop_EV,
    &SGF_prop_FF,
    &SGF_prop_FG,
    &SGF_prop_GB,
    &SGF_prop_GC,
    &SGF_prop_GM,
    &SGF_prop_GN,
    &SGF_prop_GW,
    &SGF_prop_HA,
    &SGF_prop_HO,
    &SGF_prop_IP,
    &SGF_prop_IT,
    &SGF_prop_IY,
    &SGF_prop_KM,
    &SGF_prop_KO,
    &SGF_prop_LB,
    &SGF_prop_LN,
    &SGF_prop_MA,
    &SGF_prop_MN,
    &SGF_prop_N ,
    &SGF_prop_OB,
    &SGF_prop_OH,
    &SGF_prop_ON,
    &SGF_prop_OT,
    &SGF_prop_OW,
    &SGF_prop_PB,
    &SGF_prop_PC,
    &SGF_prop_PL,
    &SGF_prop_PM,
    &SGF_prop_PW,
    &SGF_prop_RE,
    &SGF_prop_RO,
    &SGF_prop_RU,
    &SGF_prop_S ,
    &SGF_prop_SE,
    &SGF_prop_SL,
    &SGF_prop_SO,
    &SGF_prop_SQ,
    &SGF_prop_ST,
    &SGF_prop_SU,
    &SGF_prop_SZ,
    &SGF_prop_TB,
    &SGF_prop_TE,
    &SGF_prop_TM,
    &SGF_prop_TR,
    &SGF_prop_TW,
    &SGF_prop_UC,
    &SGF_prop_US,
    &SGF_prop_V ,
    &SGF_prop_VW,
    &SGF_prop_W ,
    &SGF_prop_WB,
    &SGF_prop_WC,
    &SGF_prop_WL,
    &SGF_prop_WO,
    &SGF_prop_WR,
    &SGF_prop_WT,
    &SGF_prop_WW
};
